#!/usr/bin/env ruby
#ft:ruby

# This script is to make it easier to portion out my food
# in the proper ratio for burning fat for my body

# how many calories you can eat in a day
total_calories = ARGV[0] || 2092 # my default calories right now

# percentages
fat = [0.30, 0.40]
carb = [0.10,0.30]
protein = [0.40,0.50]

# Total for the day
total_fat_day = total_calories.to_i * (fat[0]).to_f
total_carb_day = total_calories.to_i * (carb[0]).to_f
total_protein_day = (total_calories.to_i * protein[1]).to_f

# Per meal 
fat_meal = total_fat_day / 5
carb_meal = total_carb_day / 5
protein_meal = total_protein_day / 5

puts ""
puts "Fat (calories) for the day: %.2f" % total_fat_day
puts "Carb (calories) for the day:  %.2f" % total_carb_day
puts "Protein (calories) for the day: %.2f" % total_protein_day
puts ""
puts "=============================================="
puts ""
puts "Fat (calories) per meal @ 5 meals: %.2f" % fat_meal
puts "Carb (calories) per meal @ 5 meals: %.2f" % carb_meal
puts "Protein (calories) per meal @ 5 meals: %.2f" % protein_meal 
puts ""
puts "----------------------------------------------"
puts "Calories for the day: #{total_calories}"
puts ""

