#!/usr/bin/perl
# colfmt - format columnar output.
# take input file with fields separated by a whitespace
# and print out in horizontally-aligned columns.

my @output; # 2d array of line, field
my @lead;   # preserved leading whitespace from each line
my @width;  # width width of each column

while (<>) {
  chomp;

  # strip but remember leading whitespace
  my $lead = s/^(\s+)// ? $1 : '';
  push @lead, $lead;

  push @output, [my @f = grep { $_ } split /\s+/,$_];
  for (my $i=0; $i<@f; ++$i) {
    if ( (my $l = length $f[$i]) > $width[$i] )
    {
      $width[$i] = $l;
    }
  }
}

my $last = $.;
for (my $i=0; $i < @output; ++$i) {
  my $row = $output[$i];
  print $lead[$i];
  for (my $j=0; $j < @{$row} - 1; ++$j) {
    printf "%-${\($width[$j]+1)}s", $row->[$j];
  }
  print ' ', $row->[-1], "\n";
}
