#!/bin/bash
cd $CHEF/org/chef-services/56m
index=$1
elastic_nodes=$(knife node list | grep -i logstash-elastic)
for i in $elastic_nodes; do
  let result=$(ping -c 1 $i | awk 'NR==5 { print $7 }' | sed -e 's/\.0%//')
  if (( $result == 0 )); then
    curl -XDELETE http://$i:9200/$index
  fi
done
cd - > /dev/null 2>&1
