#!/bin/bash

echo "Retrieving pending tasks ...." 
if (( $# == 0 )); then 
  # assume we want the short format
  curl -s -XGET "http://elastic-client-prod-1.56m.vgtf.net:9200/_cat/pending_tasks?v"
elif [[ $1 == "long" ]]; then 
  curl -s -XGET "http://elastic-client-prod-1.56m.vgtf.net:9200/_cluster/pending_tasks?pretty"
fi
