#!/bin/bash
cd $CHEF/org/chef-services/56m

  status=$(curl -s elastic-client-prod-1.56m.vgtf.net:9200/_aliases | jq -r '(keys|tostring)')
  for i in "$status"; do
    echo $i
  done

cd - > /dev/null
