#!/bin/bash
# ft:bash
# this script will set links on cookbooks if they don't exist

link_dir="/Users/mgibson/repos/turner/syms/"
cookbook_dir="/Users/mgibson/repos/turner/cookbooks/"
cookbooks_list=$(for i in $(ls $cookbook_dir); do echo "${i##cookbook-}" ; done | xargs ) 

for i in $cookbooks_list; do
  ls $link_dir | grep -i $i > /dev/null 2>&1
  if (( $? != 0 )); then
    #logger -p local3.info "Missing link for $i"
    echo "Missing link for ${i}"
  fi
done



