#!/bin/bash
# script to reroute elasticsearch indexes that are Unassigned
usage(){ 
  echo "Usage: $0 [ <node> <sendto> ]" 
}
if (( $# == 0 )); then
  usage
else
  NODE=$1
  SENDTO=$2
  IFS=$'\n'
  while read index shard ; do # localhost needs to be changed here as well.
    curl -XPOST "$NODE:9200/_cluster/reroute" -d '{
       "commands": [
          {
              "allocate": {
                  "index": "'$INDEX'",
                  "shard": '$SHARD',
                  "node": "'$SENDTO'",
                  "allow_primary": true
            }
          }
      ]
    }'
  done <<< $(curl -s "$NODE:9200/_cat/shards" | fgrep UNASSIGNED | awk '{ print $1, $2 }')
fi
